// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objFile.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "objFile.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DvObjecFile {
class ProgramDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Program> {
} _Program_default_instance_;
class StringsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Strings> {
} _Strings_default_instance_;
class CodeDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Code> {
} _Code_default_instance_;

namespace protobuf_objFile_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Program, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Program, signature_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Program, size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Program, mainp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Program, strings_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Program, code_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strings, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Strings, inst_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Code, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Code, inst_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Program)},
  { 10, -1, sizeof(Strings)},
  { 16, -1, sizeof(Code)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Program_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Strings_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Code_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "objFile.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _Program_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Strings_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _Code_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Program_default_instance_.DefaultConstruct();
  _Strings_default_instance_.DefaultConstruct();
  _Code_default_instance_.DefaultConstruct();
  _Program_default_instance_.get_mutable()->strings_ = const_cast< ::DvObjecFile::Strings*>(
      ::DvObjecFile::Strings::internal_default_instance());
  _Program_default_instance_.get_mutable()->code_ = const_cast< ::DvObjecFile::Code*>(
      ::DvObjecFile::Code::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\robjFile.proto\022\013DvObjecFile\"\201\001\n\007Program"
      "\022\021\n\tsignature\030\001 \001(\t\022\014\n\004size\030\002 \001(\005\022\r\n\005mai"
      "np\030\003 \001(\005\022%\n\007strings\030\004 \001(\0132\024.DvObjecFile."
      "Strings\022\037\n\004code\030\005 \001(\0132\021.DvObjecFile.Code"
      "\"\027\n\007Strings\022\014\n\004inst\030\001 \003(\t\"\024\n\004Code\022\014\n\004ins"
      "t\030\001 \003(\003B-\n(orchi.DvVm.Compiler.Program.D"
      "vObjectFile\370\001\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 262);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "objFile.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_objFile_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Program::kSignatureFieldNumber;
const int Program::kSizeFieldNumber;
const int Program::kMainpFieldNumber;
const int Program::kStringsFieldNumber;
const int Program::kCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Program::Program()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_objFile_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:DvObjecFile.Program)
}
Program::Program(const Program& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  signature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.signature().size() > 0) {
    signature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.signature_);
  }
  if (from.has_strings()) {
    strings_ = new ::DvObjecFile::Strings(*from.strings_);
  } else {
    strings_ = NULL;
  }
  if (from.has_code()) {
    code_ = new ::DvObjecFile::Code(*from.code_);
  } else {
    code_ = NULL;
  }
  ::memcpy(&size_, &from.size_,
    reinterpret_cast<char*>(&mainp_) -
    reinterpret_cast<char*>(&size_) + sizeof(mainp_));
  // @@protoc_insertion_point(copy_constructor:DvObjecFile.Program)
}

void Program::SharedCtor() {
  signature_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&strings_, 0, reinterpret_cast<char*>(&mainp_) -
    reinterpret_cast<char*>(&strings_) + sizeof(mainp_));
  _cached_size_ = 0;
}

Program::~Program() {
  // @@protoc_insertion_point(destructor:DvObjecFile.Program)
  SharedDtor();
}

void Program::SharedDtor() {
  signature_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete strings_;
  }
  if (this != internal_default_instance()) {
    delete code_;
  }
}

void Program::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Program::descriptor() {
  protobuf_objFile_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_objFile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Program& Program::default_instance() {
  protobuf_objFile_2eproto::InitDefaults();
  return *internal_default_instance();
}

Program* Program::New(::google::protobuf::Arena* arena) const {
  Program* n = new Program;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Program::Clear() {
// @@protoc_insertion_point(message_clear_start:DvObjecFile.Program)
  signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && strings_ != NULL) {
    delete strings_;
  }
  strings_ = NULL;
  if (GetArenaNoVirtual() == NULL && code_ != NULL) {
    delete code_;
  }
  code_ = NULL;
  ::memset(&size_, 0, reinterpret_cast<char*>(&mainp_) -
    reinterpret_cast<char*>(&size_) + sizeof(mainp_));
}

bool Program::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DvObjecFile.Program)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string signature = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_signature()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->signature().data(), this->signature().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DvObjecFile.Program.signature"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 size = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 mainp = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mainp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DvObjecFile.Strings strings = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_strings()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DvObjecFile.Code code = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_code()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DvObjecFile.Program)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DvObjecFile.Program)
  return false;
#undef DO_
}

void Program::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DvObjecFile.Program)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string signature = 1;
  if (this->signature().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->signature().data(), this->signature().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DvObjecFile.Program.signature");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->signature(), output);
  }

  // int32 size = 2;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->size(), output);
  }

  // int32 mainp = 3;
  if (this->mainp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->mainp(), output);
  }

  // .DvObjecFile.Strings strings = 4;
  if (this->has_strings()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->strings_, output);
  }

  // .DvObjecFile.Code code = 5;
  if (this->has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->code_, output);
  }

  // @@protoc_insertion_point(serialize_end:DvObjecFile.Program)
}

::google::protobuf::uint8* Program::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DvObjecFile.Program)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string signature = 1;
  if (this->signature().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->signature().data(), this->signature().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DvObjecFile.Program.signature");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->signature(), target);
  }

  // int32 size = 2;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->size(), target);
  }

  // int32 mainp = 3;
  if (this->mainp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->mainp(), target);
  }

  // .DvObjecFile.Strings strings = 4;
  if (this->has_strings()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->strings_, deterministic, target);
  }

  // .DvObjecFile.Code code = 5;
  if (this->has_code()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->code_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DvObjecFile.Program)
  return target;
}

size_t Program::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DvObjecFile.Program)
  size_t total_size = 0;

  // string signature = 1;
  if (this->signature().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->signature());
  }

  // .DvObjecFile.Strings strings = 4;
  if (this->has_strings()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->strings_);
  }

  // .DvObjecFile.Code code = 5;
  if (this->has_code()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->code_);
  }

  // int32 size = 2;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->size());
  }

  // int32 mainp = 3;
  if (this->mainp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mainp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Program::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DvObjecFile.Program)
  GOOGLE_DCHECK_NE(&from, this);
  const Program* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Program>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DvObjecFile.Program)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DvObjecFile.Program)
    MergeFrom(*source);
  }
}

void Program::MergeFrom(const Program& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DvObjecFile.Program)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.signature().size() > 0) {

    signature_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.signature_);
  }
  if (from.has_strings()) {
    mutable_strings()->::DvObjecFile::Strings::MergeFrom(from.strings());
  }
  if (from.has_code()) {
    mutable_code()->::DvObjecFile::Code::MergeFrom(from.code());
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
  if (from.mainp() != 0) {
    set_mainp(from.mainp());
  }
}

void Program::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DvObjecFile.Program)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Program::CopyFrom(const Program& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DvObjecFile.Program)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Program::IsInitialized() const {
  return true;
}

void Program::Swap(Program* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Program::InternalSwap(Program* other) {
  signature_.Swap(&other->signature_);
  std::swap(strings_, other->strings_);
  std::swap(code_, other->code_);
  std::swap(size_, other->size_);
  std::swap(mainp_, other->mainp_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Program::GetMetadata() const {
  protobuf_objFile_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_objFile_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Program

// string signature = 1;
void Program::clear_signature() {
  signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Program::signature() const {
  // @@protoc_insertion_point(field_get:DvObjecFile.Program.signature)
  return signature_.GetNoArena();
}
void Program::set_signature(const ::std::string& value) {
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DvObjecFile.Program.signature)
}
#if LANG_CXX11
void Program::set_signature(::std::string&& value) {
  
  signature_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DvObjecFile.Program.signature)
}
#endif
void Program::set_signature(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DvObjecFile.Program.signature)
}
void Program::set_signature(const char* value, size_t size) {
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DvObjecFile.Program.signature)
}
::std::string* Program::mutable_signature() {
  
  // @@protoc_insertion_point(field_mutable:DvObjecFile.Program.signature)
  return signature_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Program::release_signature() {
  // @@protoc_insertion_point(field_release:DvObjecFile.Program.signature)
  
  return signature_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Program::set_allocated_signature(::std::string* signature) {
  if (signature != NULL) {
    
  } else {
    
  }
  signature_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), signature);
  // @@protoc_insertion_point(field_set_allocated:DvObjecFile.Program.signature)
}

// int32 size = 2;
void Program::clear_size() {
  size_ = 0;
}
::google::protobuf::int32 Program::size() const {
  // @@protoc_insertion_point(field_get:DvObjecFile.Program.size)
  return size_;
}
void Program::set_size(::google::protobuf::int32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:DvObjecFile.Program.size)
}

// int32 mainp = 3;
void Program::clear_mainp() {
  mainp_ = 0;
}
::google::protobuf::int32 Program::mainp() const {
  // @@protoc_insertion_point(field_get:DvObjecFile.Program.mainp)
  return mainp_;
}
void Program::set_mainp(::google::protobuf::int32 value) {
  
  mainp_ = value;
  // @@protoc_insertion_point(field_set:DvObjecFile.Program.mainp)
}

// .DvObjecFile.Strings strings = 4;
bool Program::has_strings() const {
  return this != internal_default_instance() && strings_ != NULL;
}
void Program::clear_strings() {
  if (GetArenaNoVirtual() == NULL && strings_ != NULL) delete strings_;
  strings_ = NULL;
}
const ::DvObjecFile::Strings& Program::strings() const {
  // @@protoc_insertion_point(field_get:DvObjecFile.Program.strings)
  return strings_ != NULL ? *strings_
                         : *::DvObjecFile::Strings::internal_default_instance();
}
::DvObjecFile::Strings* Program::mutable_strings() {
  
  if (strings_ == NULL) {
    strings_ = new ::DvObjecFile::Strings;
  }
  // @@protoc_insertion_point(field_mutable:DvObjecFile.Program.strings)
  return strings_;
}
::DvObjecFile::Strings* Program::release_strings() {
  // @@protoc_insertion_point(field_release:DvObjecFile.Program.strings)
  
  ::DvObjecFile::Strings* temp = strings_;
  strings_ = NULL;
  return temp;
}
void Program::set_allocated_strings(::DvObjecFile::Strings* strings) {
  delete strings_;
  strings_ = strings;
  if (strings) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DvObjecFile.Program.strings)
}

// .DvObjecFile.Code code = 5;
bool Program::has_code() const {
  return this != internal_default_instance() && code_ != NULL;
}
void Program::clear_code() {
  if (GetArenaNoVirtual() == NULL && code_ != NULL) delete code_;
  code_ = NULL;
}
const ::DvObjecFile::Code& Program::code() const {
  // @@protoc_insertion_point(field_get:DvObjecFile.Program.code)
  return code_ != NULL ? *code_
                         : *::DvObjecFile::Code::internal_default_instance();
}
::DvObjecFile::Code* Program::mutable_code() {
  
  if (code_ == NULL) {
    code_ = new ::DvObjecFile::Code;
  }
  // @@protoc_insertion_point(field_mutable:DvObjecFile.Program.code)
  return code_;
}
::DvObjecFile::Code* Program::release_code() {
  // @@protoc_insertion_point(field_release:DvObjecFile.Program.code)
  
  ::DvObjecFile::Code* temp = code_;
  code_ = NULL;
  return temp;
}
void Program::set_allocated_code(::DvObjecFile::Code* code) {
  delete code_;
  code_ = code;
  if (code) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:DvObjecFile.Program.code)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Strings::kInstFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Strings::Strings()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_objFile_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:DvObjecFile.Strings)
}
Strings::Strings(const Strings& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      inst_(from.inst_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:DvObjecFile.Strings)
}

void Strings::SharedCtor() {
  _cached_size_ = 0;
}

Strings::~Strings() {
  // @@protoc_insertion_point(destructor:DvObjecFile.Strings)
  SharedDtor();
}

void Strings::SharedDtor() {
}

void Strings::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Strings::descriptor() {
  protobuf_objFile_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_objFile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Strings& Strings::default_instance() {
  protobuf_objFile_2eproto::InitDefaults();
  return *internal_default_instance();
}

Strings* Strings::New(::google::protobuf::Arena* arena) const {
  Strings* n = new Strings;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Strings::Clear() {
// @@protoc_insertion_point(message_clear_start:DvObjecFile.Strings)
  inst_.Clear();
}

bool Strings::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DvObjecFile.Strings)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string inst = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_inst()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->inst(this->inst_size() - 1).data(),
            this->inst(this->inst_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DvObjecFile.Strings.inst"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DvObjecFile.Strings)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DvObjecFile.Strings)
  return false;
#undef DO_
}

void Strings::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DvObjecFile.Strings)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string inst = 1;
  for (int i = 0, n = this->inst_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->inst(i).data(), this->inst(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DvObjecFile.Strings.inst");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->inst(i), output);
  }

  // @@protoc_insertion_point(serialize_end:DvObjecFile.Strings)
}

::google::protobuf::uint8* Strings::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DvObjecFile.Strings)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string inst = 1;
  for (int i = 0, n = this->inst_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->inst(i).data(), this->inst(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DvObjecFile.Strings.inst");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->inst(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DvObjecFile.Strings)
  return target;
}

size_t Strings::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DvObjecFile.Strings)
  size_t total_size = 0;

  // repeated string inst = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->inst_size());
  for (int i = 0, n = this->inst_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->inst(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Strings::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DvObjecFile.Strings)
  GOOGLE_DCHECK_NE(&from, this);
  const Strings* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Strings>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DvObjecFile.Strings)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DvObjecFile.Strings)
    MergeFrom(*source);
  }
}

void Strings::MergeFrom(const Strings& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DvObjecFile.Strings)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  inst_.MergeFrom(from.inst_);
}

void Strings::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DvObjecFile.Strings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Strings::CopyFrom(const Strings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DvObjecFile.Strings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Strings::IsInitialized() const {
  return true;
}

void Strings::Swap(Strings* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Strings::InternalSwap(Strings* other) {
  inst_.InternalSwap(&other->inst_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Strings::GetMetadata() const {
  protobuf_objFile_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_objFile_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Strings

// repeated string inst = 1;
int Strings::inst_size() const {
  return inst_.size();
}
void Strings::clear_inst() {
  inst_.Clear();
}
const ::std::string& Strings::inst(int index) const {
  // @@protoc_insertion_point(field_get:DvObjecFile.Strings.inst)
  return inst_.Get(index);
}
::std::string* Strings::mutable_inst(int index) {
  // @@protoc_insertion_point(field_mutable:DvObjecFile.Strings.inst)
  return inst_.Mutable(index);
}
void Strings::set_inst(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:DvObjecFile.Strings.inst)
  inst_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void Strings::set_inst(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:DvObjecFile.Strings.inst)
  inst_.Mutable(index)->assign(std::move(value));
}
#endif
void Strings::set_inst(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  inst_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:DvObjecFile.Strings.inst)
}
void Strings::set_inst(int index, const char* value, size_t size) {
  inst_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:DvObjecFile.Strings.inst)
}
::std::string* Strings::add_inst() {
  // @@protoc_insertion_point(field_add_mutable:DvObjecFile.Strings.inst)
  return inst_.Add();
}
void Strings::add_inst(const ::std::string& value) {
  inst_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:DvObjecFile.Strings.inst)
}
#if LANG_CXX11
void Strings::add_inst(::std::string&& value) {
  inst_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:DvObjecFile.Strings.inst)
}
#endif
void Strings::add_inst(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  inst_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:DvObjecFile.Strings.inst)
}
void Strings::add_inst(const char* value, size_t size) {
  inst_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:DvObjecFile.Strings.inst)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
Strings::inst() const {
  // @@protoc_insertion_point(field_list:DvObjecFile.Strings.inst)
  return inst_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
Strings::mutable_inst() {
  // @@protoc_insertion_point(field_mutable_list:DvObjecFile.Strings.inst)
  return &inst_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Code::kInstFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Code::Code()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_objFile_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:DvObjecFile.Code)
}
Code::Code(const Code& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      inst_(from.inst_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:DvObjecFile.Code)
}

void Code::SharedCtor() {
  _cached_size_ = 0;
}

Code::~Code() {
  // @@protoc_insertion_point(destructor:DvObjecFile.Code)
  SharedDtor();
}

void Code::SharedDtor() {
}

void Code::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Code::descriptor() {
  protobuf_objFile_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_objFile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Code& Code::default_instance() {
  protobuf_objFile_2eproto::InitDefaults();
  return *internal_default_instance();
}

Code* Code::New(::google::protobuf::Arena* arena) const {
  Code* n = new Code;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Code::Clear() {
// @@protoc_insertion_point(message_clear_start:DvObjecFile.Code)
  inst_.Clear();
}

bool Code::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DvObjecFile.Code)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int64 inst = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_inst())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(8u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 1, 10u, input, this->mutable_inst())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DvObjecFile.Code)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DvObjecFile.Code)
  return false;
#undef DO_
}

void Code::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DvObjecFile.Code)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int64 inst = 1;
  if (this->inst_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_inst_cached_byte_size_);
  }
  for (int i = 0, n = this->inst_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64NoTag(
      this->inst(i), output);
  }

  // @@protoc_insertion_point(serialize_end:DvObjecFile.Code)
}

::google::protobuf::uint8* Code::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DvObjecFile.Code)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int64 inst = 1;
  if (this->inst_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _inst_cached_byte_size_, target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt64NoTagToArray(this->inst_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DvObjecFile.Code)
  return target;
}

size_t Code::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DvObjecFile.Code)
  size_t total_size = 0;

  // repeated int64 inst = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int64Size(this->inst_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _inst_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Code::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DvObjecFile.Code)
  GOOGLE_DCHECK_NE(&from, this);
  const Code* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Code>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DvObjecFile.Code)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DvObjecFile.Code)
    MergeFrom(*source);
  }
}

void Code::MergeFrom(const Code& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DvObjecFile.Code)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  inst_.MergeFrom(from.inst_);
}

void Code::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DvObjecFile.Code)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Code::CopyFrom(const Code& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DvObjecFile.Code)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Code::IsInitialized() const {
  return true;
}

void Code::Swap(Code* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Code::InternalSwap(Code* other) {
  inst_.InternalSwap(&other->inst_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Code::GetMetadata() const {
  protobuf_objFile_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_objFile_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Code

// repeated int64 inst = 1;
int Code::inst_size() const {
  return inst_.size();
}
void Code::clear_inst() {
  inst_.Clear();
}
::google::protobuf::int64 Code::inst(int index) const {
  // @@protoc_insertion_point(field_get:DvObjecFile.Code.inst)
  return inst_.Get(index);
}
void Code::set_inst(int index, ::google::protobuf::int64 value) {
  inst_.Set(index, value);
  // @@protoc_insertion_point(field_set:DvObjecFile.Code.inst)
}
void Code::add_inst(::google::protobuf::int64 value) {
  inst_.Add(value);
  // @@protoc_insertion_point(field_add:DvObjecFile.Code.inst)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
Code::inst() const {
  // @@protoc_insertion_point(field_list:DvObjecFile.Code.inst)
  return inst_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
Code::mutable_inst() {
  // @@protoc_insertion_point(field_mutable_list:DvObjecFile.Code.inst)
  return &inst_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace DvObjecFile

// @@protoc_insertion_point(global_scope)
